variable "access_key" {}
variable "secret_key" {}
variable "region" {}
variable "availability_zone" {}
variable "instance_type" {}
variable "key_file" {}
variable "key_name" {}
variable "subnet_id" {}
variable "security_id" {}
variable "redis_endpoint" {}
variable "redis_port" {}
variable "aws_bucket" {}
